#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages
import os
import requirements as reqs

here = os.path.abspath(os.path.dirname(__file__))

with open(os.path.join(here, "README.md")) as f:
    readme = f.read()

with open(os.path.join(here, "requirements.txt")) as f:
    requirements = [r.line for r in reqs.parse(f)]

with open(os.path.join(here, "requirements_dev.txt")) as f:
    test_requirements = [r.line for r in reqs.parse(f)]


setup(
    name="exampleenginepythonqiyhbwvw",
    version="0.1.0",
    description="Sandbox autogenerated project",
    install_requires=requirements,
    tests_require=test_requirements,
    test_suite="tests",
    packages=find_packages(),
    include_package_data=True,
    data_files=[("", [".sandbox"])],
    entry_points={
        "console_scripts": ["run_version=exampleenginepythonqiyhbwvw.main:main"]
    },
)
