from exampleenginepythonqiyhbwvw.common.field import Field

cod_client = Field("cod_client")
nombre = Field("nombre")
edad = Field("edad")
provincia = Field("provincia")
cod_postal = Field("cod_postal")
vip = Field("vip")
cod_iuc = Field("cod_iuc")
cod_titular = Field("cod_titular")
cod_producto = Field("cod_producto")
fec_alta = Field("fec_alta")
activo = Field("activo")
desc_producto = Field("desc_producto")


### mios
# phones
brand = Field("brand")
model = Field("model")
operative_system = Field("operative_system")
os_version = Field("os_version")
internal_memory = Field("internal_memory")
audio_jack = Field("audio_jack")
nfc = Field("nfc")
customer_id = Field("customer_id")
country_code = Field("country_code")
branch_id = Field("branch_id")
stock_number = Field("stock_number")
sold_product_number = Field("sold_product_number")
discount_amount = Field("discount_amount")
prime = Field("prime")
taxes = Field("taxes")
price_product = Field("price_product")
delivery_id = Field("delivery_id")
purchase_date = Field("purchase_date")
cutoff_date = Field("cutoff_date")

# customers
zipcode = Field("zipcode")
city_name = Field("city_name")
street_name = Field("street_name")
credit_card_number = Field("credit_card_number")
credit_provider_name = Field("credit_provider_name")
company_name = Field("company_name")
company_email = Field("company_email")
last_name = Field("last_name")
first_name = Field("first_name")
birth_date = Field("birth_date")
gl_date = Field("gl_date")
