from exampleenginepythonqiyhbwvw.common.field import Field

cod_producto = Field("cod_producto")
cod_iuc = Field("cod_iuc")
cod_titular = Field("cod_titular")
fec_alta = Field("fec_alta")
activo = Field("activo")
cod_client = Field("cod_client")
nombre = Field("nombre")
edad = Field("edad")
provincia = Field("provincia")
cod_postal = Field("cod_postal")
vip = Field("vip")
desc_producto = Field("desc_producto")
hash = Field("hash")

# Ejercicios
discount_extra = Field("discount_extra")
final_price = Field("final_price")
top_50 = Field("Top_50")
jwk_date = Field("jwk_date")
birthd1 = Field("birthd1")
age = Field("age")

city_name = Field("city_name")
street_name = Field("street_name")
credit_card_number = Field("credit_card_number")
last_name = Field("last_name")
first_name = Field("first_name")
brand = Field("brand")
model = Field("model")
nfc = Field("nfc")
country_code = Field("country_code")
prime = Field("prime")
customer_vip = Field("customer_vip")
taxes = Field("taxes")
price_product = Field("price_product")
discount_amount = Field("discount_amount")
extra_discount = Field("extra_discount")
brands_top = Field("brands_top")

